### ISSUE TITLE
Example for retargeting

### ISSUE THREAD

**Issue by gemlongman** [eherr/anim_utils#1]
could you offer some exampl for retargeting animation form a bvh to another, which is between different skeletons.

**Comment by eherr** [comment]
I have uploaded now an example to the following repository:
https://github.com/eherr/anim_utils_scripts

**Comment by gemlongman** [comment]
> I have uploaded now an example to the following repository:
> https://github.com/eherr/anim_utils_scripts

It‘s great~ Thank you so much!
By the way, is there some methods could automatically get skeleton model json file?
It seems  that the motion preprocessing tool couldn't export a custom skeleton model json file:
![image](https://user-images.githubusercontent.com/12515180/77151006-0ce07580-6ad0-11ea-8920-6d2d788a1c65.png)

**Comment by eherr** [comment]
Yes you can create a, new skeleton model by pressing on the "add new model" button. It will export a json file into the directory data/skeletons. You can then later edit it by selecting it from the drop down list and pressing on the "edit model" button.

**Comment by eherr** [comment]
In the skeleton model editor you need to assign a default joint name to the joints you want to be taken into account and set the coordinate system for each joint. The green axis represents the twist axis and the red axis the twist axis.

After you have assigned the left_hip, right_hip and head. You can let the tool guess the coordinate system automatically so you only have to apply corrections.

**Comment by gemlongman** [comment]
>  The green axis represents the twist axis and the red axis the twist axis.
>
> After you have assigned the left_hip, right_hip and head. You can let the tool guess the coordinate system automatically so you only have to apply corrections.

Wow! this's so helpful! Thank you so much!

**Comment by eherr** [comment]
You are welcome! 
Sorry I made a mistake in the earlier comment: green is the twist axis and red is the swing axis. You also might have to restart the tool after setting the joint mapping to let it reload the model due to a bug.

**Comment by gemlongman** [comment]
> green is the twist axis and red is the swing axis. You also might have to restart the tool after setting the joint mapping to let it reload the model due to a bug.

Got it~ I have noticed the axis and will pay more attention on it. The bug actually is not very serious, but thank you for reminding.
