### ISSUE TITLE
Is there any better way to guess local_cos

### ISSUE THREAD

**Issue by gemlongman** [eherr/anim_utils#2]
https://github.com/eherr/anim_utils/blob/c7849651f36fe18d425b8bacbbc7221ff2c41d66/retargeting/analytical.py#L139

Sorry to bother you:

1. When I used motion_preprocessing_tool create a skeleton model and used it to retargeting, there were some wrong with the output motion as shown below. Because the dest skeleton has finger joints and eye joints, hand joints and head joint didn't get suitable child for calculating y-axis. That led to head tilt and hand flip. 
Will it be better that use parent joint's y_aixs and orientation when there are more than one children?

2. By the way. Maybe I did not match right for the sole of the foot, so the feet become floating. While it is excepted the heel should be higher than the sole of the foot.  This problem actually does not matter.

![image](https://user-images.githubusercontent.com/12515180/82653258-85d78700-9c51-11ea-825c-8b8a8f80cce6.png)
This is the example files in case you are interested in my problem.
[example.zip](https://github.com/eherr/anim_utils/files/4667182/example.zip)

**Comment by eherr** [comment]
Yes in those cases the guess does not work correctly. I usually manually correct the guess in the skeleton editor by rotating the coordinate system of the problematic joints using the rotate buttons.

![manual_fix](https://user-images.githubusercontent.com/14311090/82663251-97a83280-9c2f-11ea-9c57-50ca76b57a28.png)

**Comment by eherr** [comment]
Regarding the feet you can use the button align to z axis to align the feet coordinate system to the ground:
![aling_to_z_axis](https://user-images.githubusercontent.com/14311090/82664323-c0312c00-9c31-11ea-95cf-3349ee4ccc30.png)

I have uploaded a manually edited configuration file and example output:

[manual_fix.zip](https://github.com/eherr/anim_utils/files/4667887/manual_fix.zip)

**Comment by gemlongman** [comment]
Thank you very much for all of that!
